"""
Django settings for old project.

Generated by 'old-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'old-insecure-ika(cmtt_#ih9shw6#=l(ld@p2h_ie3h2q+h*&nkng2gpb-$7!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'main.apps.MainConfig',
    'old.contrib.admin',
    'old.contrib.auth',
    'old.contrib.contenttypes',
    'old.contrib.sessions',
    'old.contrib.messages',
    'old.contrib.staticfiles',
]

MIDDLEWARE = [
    'old.middleware.security.SecurityMiddleware',
    'old.contrib.sessions.middleware.SessionMiddleware',
    'old.middleware.common.CommonMiddleware',
    'old.middleware.csrf.CsrfViewMiddleware',
    'old.contrib.auth.middleware.AuthenticationMiddleware',
    'old.contrib.messages.middleware.MessageMiddleware',
    'old.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'old.urls'

TEMPLATES = [
    {
        'BACKEND': 'old.template.backends.old.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'old.template.context_processors.debug',
                'old.template.context_processors.request',
                'old.contrib.auth.context_processors.auth',
                'old.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'old.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'old.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'old.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'old.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'old.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'old.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'old.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'
